Updated cluster blueprint resource to facilitate create and delete of cluster blueprints
HewlettPackard/hpegl-containers-terraform-resources pull request #19
Opened 2022-05-24 12:13 UTC by kjrach

2022-05-24 12:39 UTC, parekhha requested changes

2022-05-24 12:39 UTC, parekhha commented on examples/resources/hpegl_caas_cluster_blueprint/resource.tf
> +  cluster_provider = ""
Do we have to provider id here ?

2022-05-24 12:39 UTC, parekhha commented on examples/resources/hpegl_caas_cluster_blueprint/resource.tf
> +  worker_nodes {
THis is not correct it should be
worker_nodes = [ 
  {
  }
]

2022-05-24 12:39 UTC, parekhha commented on examples/resources/hpegl_caas_cluster_blueprint/resource.tf
> +    name = "master"
this should not require name.

2022-05-24 12:39 UTC, parekhha commented on internal/resources/schemas/machine_sets.go
> +			Required: true,
Is this schema used for cluster ? Do not mix schema across resources.

2022-05-25 03:31 UTC, kjrach commented on examples/resources/hpegl_caas_cluster_blueprint/resource.tf
> +  cluster_provider = ""
cluster_provider = "ecp"

2022-05-26 03:27 UTC, kjrach commented on examples/resources/hpegl_caas_cluster_blueprint/resource.tf
> +    name = "master"
Done

2022-05-26 04:02 UTC, parekhha approved these changes

2022-05-26 04:02 UTC, merged